# Generated by Django 5.1.4 on 2024-12-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('billing', 'Billing')], max_length=50)),
                ('type', models.CharField(choices=[('postal', 'Postal'), ('physical', 'Physical'), ('both', 'Both')], max_length=50)),
                ('text', models.TextField(blank=True)),
                ('line', models.JSONField(default=list)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('state', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('period', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('phone', 'Phone'), ('fax', 'Fax'), ('email', 'Email'), ('pager', 'Pager'), ('url', 'URL'), ('sms', 'SMS'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('use', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('temp', 'Temp'), ('old', 'Old'), ('mobile', 'Mobile')], max_length=20)),
                ('rank', models.PositiveIntegerField(null=True)),
                ('period', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='HumanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(choices=[('usual', 'Usual'), ('official', 'Official'), ('temp', 'Temp'), ('nickname', 'Nickname'), ('anonymous', 'Anonymous'), ('old', 'Old'), ('maiden', 'Name changed for Marriage')], max_length=50)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('family', models.CharField(blank=True, max_length=150)),
                ('given', models.JSONField(blank=True, default=list)),
                ('prefix', models.JSONField(blank=True, default=list)),
                ('suffix', models.JSONField(blank=True, default=list)),
                ('period', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('birth_date', models.DateField(blank=True)),
                ('deceased_boolean', models.BooleanField(default=False)),
                ('deceased_datetime', models.DateTimeField(blank=True)),
                ('marital_status', models.JSONField(default=dict)),
                ('multiple_birth_boolean', models.BooleanField(default=False)),
                ('multiple_birth_integer', models.IntegerField(null=True)),
                ('photo', models.JSONField(default=list)),
                ('contact', models.JSONField(default=list)),
                ('communication', models.JSONField(default=list)),
                ('general_practitioner', models.JSONField(default=list)),
                ('managing_organization', models.JSONField(default=dict)),
                ('link', models.JSONField(default=list)),
                ('address', models.ManyToManyField(related_name='patients', to='api.address')),
                ('name', models.ManyToManyField(related_name='patients', to='api.humanname')),
                ('telecom', models.ManyToManyField(related_name='patients', to='api.contactpoint')),
            ],
        ),
    ]
