# Generated by Django 5.1.4 on 2025-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='deceased_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
